# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('L', 'Leave'), ('O', 'Over Time')], max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('1', 'Approved'), ('2', 'Denied')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('entry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIP',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('IP', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Employee')),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendence_employeeip', to='attendence.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('punch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_normal', models.BooleanField(default=True)),
                ('IP', models.GenericIPAddressField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Employee')),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendence_punch', to='attendence.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=100, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='adjustmentlog',
            name='entry_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendence_adjustmentlog', to='attendence.Employee'),
        ),
        migrations.AddField(
            model_name='adjustmentlog',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Adjustment'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Employee'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='entry_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendence_adjustment', to='attendence.Employee'),
        ),
    ]
